//
// Groups different load times by country for Barchart visualization.
//
pageViews
| where isnotempty(customDimensions.entityName)
| where customDimensions.isBoot == 1
| extend ColdLatency = toreal(customDimensions.coldLatency), WarmLatency = toreal(customDimensions.warmLatency)
| summarize avgColdLoad = avg(ColdLatency),
    avgWarmLoad = avg(WarmLatency),
    avgDuration = avg(duration)
    by client_CountryOrRegion
| order by avgDuration
